# Setup
title:               Lightwick
tagline:             'For a better curiosity'
description:         'Remember to think'
url:                 https://lightwick.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# About/contact
author:
  name:              Kevin Noh
  url:               https://lightwick.github.io
  email:             smallyk99@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-8LZFXETWQQ #UA-XXXX-Y

# Build settings
markdown: kramdown
