# Setup
title:               Lightwick
tagline:             'For a better curiosity'
description:         'Trying to live life to it's fullest'
url:                 https://lightwick.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kevin Noh
  url:               https://lightwick.github.io
  email:             smallyk99@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
